// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Appeal
{
    public int AppealId { get; set; }

    public int AdjustmentId { get; set; }

    public int TeamId { get; set; }

    public string Message { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public string AdminResponse { get; set; }

    public int? ReviewedById { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public int? PenaltyAdjustmentId { get; set; }

    public virtual PenaltiesBonuse PenaltyAdjustment { get; set; }

    public virtual User ReviewedBy { get; set; }

    public virtual Team Team { get; set; }
}