// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

public partial class SealDbContext : DbContext
{
    public SealDbContext(DbContextOptions<SealDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Appeal> Appeals { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Challenge> Challenges { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<Criterion> Criteria { get; set; }

    public virtual DbSet<Hackathon> Hackathons { get; set; }

    public virtual DbSet<HackathonPhase> HackathonPhases { get; set; }

    public virtual DbSet<MentorAssignment> MentorAssignments { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<PenaltiesBonuse> PenaltiesBonuses { get; set; }

    public virtual DbSet<PhaseChallenge> PhaseChallenges { get; set; }

    public virtual DbSet<Prize> Prizes { get; set; }

    public virtual DbSet<PrizeAllocation> PrizeAllocations { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Score> Scores { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    public virtual DbSet<StudentVerification> StudentVerifications { get; set; }

    public virtual DbSet<Submission> Submissions { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamChallenge> TeamChallenges { get; set; }

    public virtual DbSet<TeamInvitation> TeamInvitations { get; set; }

    public virtual DbSet<TeamMember> TeamMembers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Appeal>(entity =>
        {
            entity.HasKey(e => e.AppealId).HasName("PK__Appeals__BB6849F01B60B3BF");

            entity.HasIndex(e => e.PenaltyAdjustmentId, "IX_Appeals_PenaltyAdjustmentId");

            entity.HasIndex(e => e.ReviewedById, "IX_Appeals_ReviewedById");

            entity.HasIndex(e => e.TeamId, "IX_Appeals_TeamId");

            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.Status).IsRequired();

            entity.HasOne(d => d.PenaltyAdjustment).WithMany(p => p.Appeals).HasForeignKey(d => d.PenaltyAdjustmentId);

            entity.HasOne(d => d.ReviewedBy).WithMany(p => p.Appeals).HasForeignKey(d => d.ReviewedById);

            entity.HasOne(d => d.Team).WithMany(p => p.Appeals).HasForeignKey(d => d.TeamId);
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__AuditLog__5E5499A8E64A6512");

            entity.HasIndex(e => e.UserId, "IX_AuditLogs_UserID");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__AuditLogs__UserI__66603565");
        });

        modelBuilder.Entity<Challenge>(entity =>
        {
            entity.HasIndex(e => e.SeasonId, "IX_Challenges_SeasonID");

            entity.HasIndex(e => e.UserId, "IX_Challenges_UserID");

            entity.Property(e => e.ChallengeId).HasColumnName("ChallengeID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FilePath).HasMaxLength(255);
            entity.Property(e => e.SeasonId).HasColumnName("SeasonID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Season).WithMany(p => p.Challenges).HasForeignKey(d => d.SeasonId);

            entity.HasOne(d => d.User).WithMany(p => p.Challenges)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.ChapterId).HasName("PK__Chapters__0893A34AE9078E94");

            entity.HasIndex(e => e.LeaderId, "IX_Chapters_LeaderID");

            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.ChapterName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.LeaderId).HasColumnName("LeaderID");

            entity.HasOne(d => d.Leader).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.LeaderId)
                .HasConstraintName("FK__Chapters__Leader__2D27B809");
        });

        modelBuilder.Entity<Criterion>(entity =>
        {
            entity.HasKey(e => e.CriteriaId).HasName("PK__Criteria__FE6ADB2DCBE7CEED");

            entity.HasIndex(e => e.HackathonId, "IX_Criteria_HackathonID");

            entity.Property(e => e.CriteriaId).HasColumnName("CriteriaID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.Criteria)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Criteria__Hackat__4AB81AF0");
        });

        modelBuilder.Entity<Hackathon>(entity =>
        {
            entity.HasKey(e => e.HackathonId).HasName("PK__Hackatho__A9C9EEEBC3FD865C");

            entity.HasIndex(e => e.CreatedBy, "IX_Hackathons_CreatedBy");

            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Season).HasMaxLength(20);
            entity.Property(e => e.Theme).HasMaxLength(200);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Hackathons)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__Hackathon__Creat__3A81B327");
        });

        modelBuilder.Entity<HackathonPhase>(entity =>
        {
            entity.HasKey(e => e.PhaseId).HasName("PK__Hackatho__5BA26D42DF28EC72");

            entity.HasIndex(e => e.HackathonId, "IX_HackathonPhases_HackathonID");

            entity.Property(e => e.PhaseId).HasColumnName("PhaseID");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.PhaseName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.HackathonPhases)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Hackathon__Hacka__3D5E1FD2");
        });

        modelBuilder.Entity<MentorAssignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK__MentorAs__32499E572E4DCCFE");

            entity.HasIndex(e => e.ChapterId, "IX_MentorAssignments_ChapterID");

            entity.HasIndex(e => e.MentorId, "IX_MentorAssignments_MentorID");

            entity.HasIndex(e => e.TeamId, "IX_MentorAssignments_TeamID");

            entity.Property(e => e.AssignmentId).HasColumnName("AssignmentID");
            entity.Property(e => e.AssignedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.MentorId).HasColumnName("MentorID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");

            entity.HasOne(d => d.Chapter).WithMany(p => p.MentorAssignments)
                .HasForeignKey(d => d.ChapterId)
                .HasConstraintName("FK__MentorAss__Chapt__412EB0B6");

            entity.HasOne(d => d.Mentor).WithMany(p => p.MentorAssignments)
                .HasForeignKey(d => d.MentorId)
                .HasConstraintName("FK__MentorAss__Mento__403A8C7D");

            entity.HasOne(d => d.Team).WithMany(p => p.MentorAssignments)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__MentorAss__TeamI__4222D4EF");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E3215980F4A");

            entity.HasIndex(e => e.UserId, "IX_Notifications_UserID");

            entity.Property(e => e.NotificationId).HasColumnName("NotificationID");
            entity.Property(e => e.IsRead).HasDefaultValue(false);
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.SentAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Notificat__UserI__619B8048");
        });

        modelBuilder.Entity<PenaltiesBonuse>(entity =>
        {
            entity.HasKey(e => e.AdjustmentId).HasName("PK__Penaltie__E60DB8B3057AD2D7");

            entity.HasIndex(e => e.HackathonId, "IX_PenaltiesBonuses_HackathonID");

            entity.HasIndex(e => e.TeamId, "IX_PenaltiesBonuses_TeamID");

            entity.Property(e => e.AdjustmentId).HasColumnName("AdjustmentID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.Points).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.Type).HasMaxLength(20);

            entity.HasOne(d => d.Hackathon).WithMany(p => p.PenaltiesBonuses)
                .HasForeignKey(d => d.HackathonId)
                .HasConstraintName("FK__Penalties__Hacka__5441852A");

            entity.HasOne(d => d.Team).WithMany(p => p.PenaltiesBonuses)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__Penalties__TeamI__534D60F1");
        });

        modelBuilder.Entity<PhaseChallenge>(entity =>
        {
            entity.HasKey(e => e.PhaseChallengeId).HasName("PK__PhaseCha__9A75B672A3020308");

            entity.Property(e => e.AssignedAt).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.Challenge).WithMany(p => p.PhaseChallenges)
                .HasForeignKey(d => d.ChallengeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhaseChallenges_Challenge");

            entity.HasOne(d => d.Phase).WithMany(p => p.PhaseChallenges)
                .HasForeignKey(d => d.PhaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhaseChallenges_HackathonPhases");
        });

        modelBuilder.Entity<Prize>(entity =>
        {
            entity.HasKey(e => e.PrizeId).HasName("PK__Prizes__5C36F4BBB8AC2CDE");

            entity.HasIndex(e => e.HackathonId, "IX_Prizes_HackathonID");

            entity.Property(e => e.PrizeId).HasColumnName("PrizeID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.PrizeName).HasMaxLength(100);
            entity.Property(e => e.PrizeType).HasMaxLength(50);

            entity.HasOne(d => d.Hackathon).WithMany(p => p.Prizes)
                .HasForeignKey(d => d.HackathonId)
                .HasConstraintName("FK__Prizes__Hackatho__59063A47");
        });

        modelBuilder.Entity<PrizeAllocation>(entity =>
        {
            entity.HasKey(e => e.AllocationId).HasName("PK__PrizeAll__B3C6D6ABFC4D88CE");

            entity.HasIndex(e => e.PrizeId, "IX_PrizeAllocations_PrizeID");

            entity.HasIndex(e => e.TeamId, "IX_PrizeAllocations_TeamID");

            entity.HasIndex(e => e.UserId, "IX_PrizeAllocations_UserID");

            entity.Property(e => e.AllocationId).HasColumnName("AllocationID");
            entity.Property(e => e.AwardedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PrizeId).HasColumnName("PrizeID");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Prize).WithMany(p => p.PrizeAllocations)
                .HasForeignKey(d => d.PrizeId)
                .HasConstraintName("FK__PrizeAllo__Prize__5BE2A6F2");

            entity.HasOne(d => d.Team).WithMany(p => p.PrizeAllocations)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__PrizeAllo__TeamI__5CD6CB2B");

            entity.HasOne(d => d.User).WithMany(p => p.PrizeAllocations)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__PrizeAllo__UserI__5DCAEF64");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3A0C0D195B");

            entity.HasIndex(e => e.RoleName, "UQ__Roles__8A2B61609AE5555F").IsUnique();

            entity.HasIndex(e => e.RoleName, "UQ__Roles__8A2B6160D48421E9").IsUnique();

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Score>(entity =>
        {
            entity.HasKey(e => e.ScoreId).HasName("PK__Scores__7DD229F13F0683F7");

            entity.HasIndex(e => e.CriteriaId, "IX_Scores_CriteriaID");

            entity.HasIndex(e => e.JudgeId, "IX_Scores_JudgeID");

            entity.HasIndex(e => e.SubmissionId, "IX_Scores_SubmissionID");

            entity.Property(e => e.ScoreId).HasColumnName("ScoreID");
            entity.Property(e => e.CriteriaId).HasColumnName("CriteriaID");
            entity.Property(e => e.JudgeId).HasColumnName("JudgeID");
            entity.Property(e => e.Score1)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("Score");
            entity.Property(e => e.ScoredAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SubmissionId).HasColumnName("SubmissionID");

            entity.HasOne(d => d.Criteria).WithMany(p => p.Scores)
                .HasForeignKey(d => d.CriteriaId)
                .HasConstraintName("FK__Scores__Criteria__4F7CD00D");

            entity.HasOne(d => d.Judge).WithMany(p => p.Scores)
                .HasForeignKey(d => d.JudgeId)
                .HasConstraintName("FK__Scores__JudgeID__4E88ABD4");

            entity.HasOne(d => d.Submission).WithMany(p => p.Scores)
                .HasForeignKey(d => d.SubmissionId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Scores__Submissi__4D94879B");
        });

        modelBuilder.Entity<Season>(entity =>
        {
            entity.ToTable("Season");

            entity.Property(e => e.SeasonId).HasColumnName("SeasonID");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<StudentVerification>(entity =>
        {
            entity.HasKey(e => e.VerificationId).HasName("PK__StudentV__306D4907CCE0E485");

            entity.Property(e => e.BackCardImage).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FrontCardImage).HasMaxLength(500);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Major).HasMaxLength(255);
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.StudentCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StudentEmail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UniversityName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.StudentVerifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentVerification_Users");
        });

        modelBuilder.Entity<Submission>(entity =>
        {
            entity.HasKey(e => e.SubmissionId).HasName("PK__Submissi__449EE1050C9EA9BB");

            entity.HasIndex(e => e.TeamId, "IX_Submissions_TeamID");

            entity.Property(e => e.SubmissionId).HasColumnName("SubmissionID");
            entity.Property(e => e.SubmittedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.SubmittedByNavigation).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.SubmittedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Submission_User");

            entity.HasOne(d => d.Team).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__Submissio__TeamI__45F365D3");
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.TeamId).HasName("PK__Teams__123AE7B9D9A0D6C3");

            entity.HasIndex(e => e.ChapterId, "IX_Teams_ChapterID");

            entity.HasIndex(e => e.LeaderId, "IX_Teams_LeaderID");

            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.LeaderId).HasColumnName("LeaderID");
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Chapter).WithMany(p => p.Teams)
                .HasForeignKey(d => d.ChapterId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Teams__ChapterID__30F848ED");

            entity.HasOne(d => d.Leader).WithMany(p => p.Teams)
                .HasForeignKey(d => d.LeaderId)
                .HasConstraintName("FK__Teams__LeaderID__31EC6D26");
        });

        modelBuilder.Entity<TeamChallenge>(entity =>
        {
            entity.Property(e => e.RegisteredAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Status).HasDefaultValue(true);
            entity.Property(e => e.TeamId).HasColumnName("TeamID");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.TeamChallenges)
                .HasForeignKey(d => d.HackathonId)
                .HasConstraintName("FK_TeamChallenges_Hackathon");

            entity.HasOne(d => d.Phase).WithMany(p => p.TeamChallenges)
                .HasForeignKey(d => d.PhaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeamChallenge_Phase");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamChallenges).HasForeignKey(d => d.TeamId);
        });

        modelBuilder.Entity<TeamInvitation>(entity =>
        {
            entity.HasKey(e => e.InvitationId);

            entity.HasIndex(e => e.InvitedByUserId, "IX_TeamInvitations_InvitedByUserId");

            entity.HasIndex(e => e.TeamId, "IX_TeamInvitations_TeamId");

            entity.Property(e => e.InvitationId).ValueGeneratedNever();
            entity.Property(e => e.InvitedEmail).IsRequired();
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending");

            entity.HasOne(d => d.InvitedByUser).WithMany(p => p.TeamInvitations).HasForeignKey(d => d.InvitedByUserId);

            entity.HasOne(d => d.Team).WithMany(p => p.TeamInvitations).HasForeignKey(d => d.TeamId);
        });

        modelBuilder.Entity<TeamMember>(entity =>
        {
            entity.HasKey(e => new { e.TeamId, e.UserId }).HasName("PK__TeamMemb__C3426B730EB52823");

            entity.ToTable(tb => tb.HasTrigger("trg_CheckTeamSize"));

            entity.HasIndex(e => e.UserId, "IX_TeamMembers_UserID");

            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.RoleInTeam)
                .HasMaxLength(50)
                .HasDefaultValue("Member");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__TeamMembe__TeamI__35BCFE0A");

            entity.HasOne(d => d.User).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__TeamMembe__UserI__36B12243");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC6328663B");

            entity.HasIndex(e => e.RoleId, "IX_Users_RoleID");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534190B6398").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Users__A9D105347866D964").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RefreshTokenExpiryTime).HasColumnType("datetime");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Token).HasMaxLength(255);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__Users__RoleID__286302EC");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}