// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TeamChallenge
{
    public int TeamId { get; set; }

    public DateTime RegisteredAt { get; set; }

    public int TeamChallengeId { get; set; }

    public int? HackathonId { get; set; }

    public int PhaseId { get; set; }

    public bool Status { get; set; }

    public virtual Hackathon Hackathon { get; set; }

    public virtual HackathonPhase Phase { get; set; }

    public virtual Team Team { get; set; }
}